import 'package:abg_utils/abg_utils.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../main.dart';

Lang strings = Lang();

class Lang {

  var direction = TextDirection.ltr;
  var locale = "en";

  Map<int, String> langEng = {
    0: "ModjiDep",
    1: "V 1.0",
    2: "SUBMIT",
    3: "Language",
    4: "Preferred language",
    5: "Select preferred language",
    6: "Home",
    7: "Discuss",
    8: "Reservation",
    9: "Account",
    10: "Change language",
    11: "Set your preferred language",
    12: "Enable dark mode",
    13: "Set your favorite mode",
    14: "Privacy Policy",
    15: "Know our privacy policy",
    16: "Tap to view profile",
    17: "Logout",
    18: "Close the session",
    19: "Notices",
    20: "A lot of important information",
    21: "Name",
    22: "Enter your name",
    23: "Email",
    24: "Enter your Email",
    25: "Telephone number",
    26: "Enter your phone number",
    27: "Address",
    28: "Enter the customers' address",
    29: "Description",
    30: "Enter a brief description of yourself",
    31: "SAVE",
    32: "Change password",
    33: "New password",
    34: "Enter the password",
    35: "Confirm new password",
    36: "Enter the password",
    37: "CHANGE PASSWORD",
    38: "My Profile",
    39: "All About You",
    40: "critical",
    41: "Read all",
    42: "Average ratings",
    43: "Connect now",
    44: "Password",
    45: "Enter your password",
    46: "CONTINUE",
    47: "Registration",
    48: "or continue with",
    49: "Register",
    50: "in less than a minute",
    51: "Confirm password",
    52: "Verification",
    53: "We will send you the verification code.",
    54: "We sent a 6-digit verification code.",
    55: "Enter code",
    56: "Enter the 6-digit code",
    57: "Write your message...",
    58: "New",
    59: "Accepted",
    60: "In progress",
    61: "Done",
    62: "Cancelled",
    63: "History",
    64: "Call",
    65: "Message",
    66: "Identifier",
    67: "Waiting",
    68: "Reservation accepted",
    69: "Accepted on",
    70: "Start a task",
    71: "Planned",
    72: "Task completed",
    73: "Payment will appear here",
    74: "Pricing",
    75: "Quantity",
    76: "Tax amount",
    77: "Total",
    78: "Asked for",
    79: "Payment",
    80: "Make payment",
    81: "Cash payment",
    82: "Confirm payment",
    83: "Revision",
    84: "Leave a review",
    78: "Asked for",
    86: "Write your review",
    87: "Tell us about this service",
    88: "Click on the stars to rate this service",
    89: "Submit review",
    90: "Add images",
    91: "From the Gallery",
    92: "From the camera",
    93: "How can we help you?",
    94: "Find what you need",
    95: "Quick search",
    96: "Notify",
    97: "Duration",
    98: "min",
    99: "This service may take up to",
    100: "Galleries",
    101: "Reviews & Ratings",
    102: "Book this service",
    103: "Your address",
    104: "Add new",
    105: "Hint",
    106: "Is there anything else",
    107: "Coupon code",
    108: "Apply",
    109: "Anytime",
    110: "Schedule an order",
    111: "Service requested on",
    112: "Select a date and time",
    //113: "CONFIRM & BOOK NOW",
    113: "CONFIRM",
    114: "Okay",
    115: "Your reservation has been successfully submitted, you will receive a confirmation soon.",
    116: "Thank you!",
    117: "Add an address",
    118: "My house",
    119: "Full address",
    120: "Select address",
    121: "Choose here",
    122: "Search",
    123: "Monday",
    124 : "Tuesday",
    125: "Wednesday",
    126: "Thursday",
    127: "Friday",
    128: "Saturday",
    129: "Sunday",
    130: "fixed",
    131: "schedule",
    132: "start from",
    133: "Please enter the address",
    134: "Please select the address",
    135: "Please enter an email",
    136: "Please enter the password",
    137: "User not found",
    138: "User does not create",
    139: "Wrong email",
    140: "Passwords are not equal",
    141: "The phone number must be ",
    142: "symbols",
    143: "Code sent. Please check your phone for verification code.",
    144: "Time out",
    145: "Today",
    146: "About us",
    147: "We are known",
    148: "General conditions",
    149: "Known general conditions",
    150: "Not found...",
    151: "Enter password confirmation",
    152: "Password changed",
    153: "Please enter the name",
    154: "Saved data",
    155: "Supplier",
    156: "Chat Post",
    157: "The new reservation has arrived",
    158: "Status now:",
    159: "The status of the reservation has been modified",
    160: "From user:",
    161: "Rate this service",
    162: "Coupon not found",
    163: "Coupon activated",
    164: "Coupon not supported by this supplier",
    165: "Coupon does not support this category",
    166: "The coupon does not support this service",
    167: "Coupon",
    168: "no",
    169: "The coupon has expired",
    170: "Your favourites",
    171: "See your favorite services",
    172: "Superior services",
    173: "User is disabled. Log in to administrator for more information.",
    174: "Blog",
    175: "See all",
    176: "Loading...",
    177: "Consignment",
    178: "Do you want to quit ?",
    179 : "No",
    180 : "Exit",
    181 : "Filter",
    182 : "Sort by",
    183 : "Ascending (A-Z)",
    184 : "Descending (Z-A)",
    185 : "Price",
    186 : "Reset Filter",
    187 : "Apply Filter",
    188 : "My Address",
    189 : "Address not found",
    190 : "Home",
    191 : "Office",
    192 : "Other",
    193 : "Set Location",
    194 : "Find services near your",
    195 : "By allowing location access, you can search for services and providers near your.",
    196 : "Use currents location",
    197 : "Set from map",
    198 : "Your current location is now saved. If the requested Service is to be performed elsewhere, we will contact you to indicate the specific location. Press the button below to validate your request.",
    199 : "Label as",
    200 : "Delivery Address",
    201 : "Enter Delivery Address",
    202 : "Contact name",
    203 : "Enter Contact name",
    204 : "Contact phone number",
    205 : "Enter Contact phone number",
    206 : "Save location",
    207 : "Latitude",
    208 : "Longitude",
    209 : "Please enter phone",
    210 : "by administrator",
    211 : "by provider",
    212 : "by customer",
    213 : "Enter address",
    214 : "Current address",
    215 : "Other addresses",
    216 : "Location",
    217 : "Your address is outside provider work area",
    218 : "See details",
    219 : "Special Requests",
    220 : "Provider Location",
    221 : "Addons",
    222 : "Nearby you",
    223 : "Far",
    224 : "Providers",
    225 : "Please enter valid code",
    226 : "Your phone number verified. You can't edit phone number",
    227 : "Forgot password?",
    228 : "Reset password",
    229 : "Send new password",
    230 : "Reset password email sent. Please check your mail.",
    231 : "Date",
    232 : "Identifiant",
    233 : "Please enter text",
    234 : "Please enter code",
    235 : "Subtotal",
    236 : "Discount",
    237 : "Subcategory",
    238 : "Share this app",
    239 : "Services nearby",
    240 : "Open Provider Page",
    241 : "Report ...",
    242 : "Block user",
    243 : "Block",
    244 : "They won't be able to message you. You won't be able to message them. They won't be notified that you blocked them. ",
    245 : "User",
    246 : "Cancel",
    247 : "blocked",
    248 : "Why are you reporting this user?",
    249 : "Your report is anonymous, except if you're reporting an intellectual property infringement. ",
    250 : "Thanks for letting us know",
    251 : "Your feedback is important in helping us keep the community safe. ",
    252 : "Unblock",
    253 : "They be able to message you. You be able to message them. They won't be notified that you unblocked them. ",
    254 : "unblocked",
    255 : "Your Favorite Providers",
    256 : "View your favorite providers",
    257 : "Favorite Providers",
    258 : "Enable Notify",
    259 : "Not available Now",
    260 : "Services",
    261 : "Provider products",
    262 : "Not available Now",
    263 : "Total amount",
    264 : "Add to cart",
    265 : "Please select variant",
    266 : "in stock",
    267 : "Product added to cart",
    268 : "Cart",
    269 : "My Cart",
    270 : "Proceed to checkout",
    271 : "Your cart is empty",
    272 : "Item price",
    273 : "This service already in the cart",
    274 : "This product already in the cart",
    275 : "Service added to cart",
    276 : "VAT/TAX",
    277 : "See more",
    278 : "Products",
    279 : "Search products",
    280 : "Sort by provider",
    281 : "Not select",
    282 : "Related products",
    283 : "Other products",
    284 : "Booking At",
    285 : "Minimum purchase amount for this provider: ",
    286 : "Maximum purchase amount for this provider: ",
    287 : "@ ModjiDep 2022",
    288: "Perfect troubleshooting at your fingertips",
    289: "Unavailable",
    290: "Ask",
    291: "Continue",
    292: "Check your internet connection!",
    293: "By TigerSoft",
    294: "See comments",
    295: "Ready",
    296: "Finished",
    297: "Cancelled",
    298: "Accepted",
    299: "Loading messages...",
    300: "No notification",
    301: "Verification completed successfully. Welcome among us.",
    302 : "Updates are available. Go to PlayStore or appStore to get the latest version.",
    303 : "No Offer yet!",
  };







  Map<int, String> langFra = {
    0 : "ModjiDep",
    1 : "V 1.0",
    2 : "SOUMETTRE",
    3 : "Langue",
    4 : "Langue préférée",
    5 : "Sélectionner la langue préférée",
    6 : "Accueil",
    7 : "Discuter",
    8 : "Historique",
    9 : "Compte",
    10 : "Changer de langue",
    11 : "Définissez votre langue préférée",
    12 : "Activer le mode sombre",
    13 : "Définissez votre mode préféré",
    14 : "Politique de confidentialité",
    15 : "Connaître notre politique de confidentialité",
    16 : "Appuyez pour afficher le profil",
    17 : "Déconnexion",
    18 : "Fermer la session",
    19 : "Avis",
    20 : "Beaucoup d'informations importantes",
    21 : "Nom",
    22 : "Entrez votre nom",
    23 : "E-mail",
    24 : " Entrez votre e-mail ",
    25 : "Numéro de téléphone",
    26 : "Entrez votre numéro de téléphone",
    27 : "Adresse",
    28 : "Saisir l'adresse des clients",
    29 : "Description",
    30 : "Entrez une brève description de vous-même",
    31 : "SAUVEGARDER",
    32 : "Modifier le mot de passe",
    33 : "Nouveau mot de passe",
    34 : "Entrez le mot de passe",
    35 : "Confirmer le nouveau mot de passe",
    36 : "Entrez le mot de passe",
    37 : "MODIFIER MOT DE PASSE",
    38 : "Mon profil",
    39: "Tout sur vous",
    40 : "critique",
    41 : "Lire tout",
    42 : "Notes moyennes",
    43 : "Connectez-vous maintenant",
    44 : "Mot de passe",
    45 : "Entrez votre mot de passe",
    46 : "CONTINUER",
    47 : "Inscription",
    48 : "ou continuer avec",
    49 : "S'inscrire",
    50 : "en moins d'une minute",
    51 : "Confirmer le mot de passe",
    52 : "Vérification",
    53 : "Nous vous enverrons le code de vérification.",
    54 : "Nous avons envoyé un code de vérification à 6 chiffres.",
    55 : "Saisir le code",
    56 : "Entrez le code à 6 chiffres",
    57 : "Ecrivez votre message...",
    58 : "Nouveau",
    59 : "Accepté",
    60 : "En cours",
    61 : "Terminé",
    62 : "Annulé",
    63 : "Historique",
    64 : "Appeler",
    65 : "Message",
    66 : "Identifiant",
    67 : "En attente",
    68 : "Réservation acceptée",
    69 : "Accepté le",
    70 : "Démarrer une tâche",
    71 : "Prévu",
    72 : "Tâche terminée",
    73 : "Le paiement apparaîtra ici",
    74 : "Tarification",
    75 : "Quantité",
    76 : "Montant de la taxe",
    77 : "Totale",
    78 : "Demandé",
    79 : "Paiement",
    80 : "Effectuer le paiement",
    81 : "Paiement en espèces",
    82 : "Confirmer le paiement",
    83 : "Révision",
    84 : "Laisser un avis",
    78 : "Demandé",
    86 : "Écrivez votre avis",
    87 : "Parlez-nous de ce service",
    88 : "Cliquez sur les étoiles pour noter ce service",
    89 : "Envoyer l'avis",
    90 : "Ajouter des images",
    91 : "De la galerie",
    92 : "De la caméra",
    93 : "Comment pouvons-nous vous aider ?",
    94 : "Trouvez ce dont vous avez besoin",
    95 : "Recherche rapide",
    96 : "Notifier",
    97 : "Durée",
    98 : "min",
    99 : "Ce service peut prendre jusqu'à",
    100 : "Galeries",
    101 : "Avis et notes",
    102 : "Réservez ce service",
    103 : "Votre adresse",
    104 : "Ajouter nouveau",
    105 : "Indice",
    106 : "Y a-t-il autre chose ?",
    107 : "Code promo",
    108 : "Appliquer",
    109 : " N'importe quand ",
    110 : "Planifier une commande",
    111 : "Service demandé le",
    112 : "Sélectionner une date et une heure",
    //113 : "CONFIRMER ET RÉSERVER MAINTENANT",
    113 : "CONFIRMER",
    114 : "Ok",
    115 : "Votre réservation a été soumise avec succès, vous recevrez bientôt une confirmation.",
    116 : "Merci !",
    117 : "Ajouter une adresse",
    118 : "Ma maison",
    119 : "Adresse complète",
    120 : "Sélectionner l'adresse",
    121 : "Choisir ici",
    122 : "Rechercher",
    123 : "Lundi",
    124 : "mardi",
    125 : "mercredi",
    126 : "Jeudi",
    127 : "Vendredi",
    128 : "Samedi",
    129 : "dimanche",
    130 : "fixe",
    131 : "horaire",
    132 : "commencer à partir de",
    133 : "Veuillez entrer l'adresse",
    134 : "Veuillez sélectionner l'adresse",
    135 : "Veuillez saisir un e-mail",
    136 : "Veuillez entrer le mot de passe",
    137 : "Utilisateur introuvable",
    138 : "L'utilisateur ne crée pas",
    139 : "Mauvais e-mail",
    140 : "Les mots de passe ne sont pas égaux",
    141 : "Le numéro de téléphone doit être ",
    142 : "symboles",
    143 : "Code envoyé. Veuillez vérifier votre téléphone pour le code de vérification.",
    144 : "Temps mort",
    145 : "Aujourd'hui",
    146 : "À propos de nous",
    147 : "Nous sommes connus",
    148 : "Conditions générales",
    149 : "Conditions générales connues",
    150 : "Non trouvé...",
    151 : "Entrez la confirmation du mot de passe",
    152 : "Mot de passe modifié",
    153 : "Veuillez entrer le nom",
    154 : "Données enregistrées",
    155 : "Fournisseur",
    156 : " Message de discussion ",
    157 : "La nouvelle réservation est arrivée",
    158 : "État actuel : ",
    159 : "Le statut de la réservation a été modifié",
    160 : "De l'utilisateur :",
    161 : "Évaluez ce service",
    162 : "Coupon introuvable",
    163 : "Coupon activé",
    164 : "Coupon non pris en charge par ce fournisseur",
    165 : "Le coupon ne prend pas en charge cette catégorie",
    166 : "Le coupon ne prend pas en charge ce service",
    167 : "Bons",
    168 : "non",
    169 : "Le coupon a expiré",
    170 : "Vos favoris",
    171 : "Voir vos services favoris",
    172 : "Prestations supérieures ",
    173 : "L'utilisateur est désactivé. Connectez-vous à l'administrateur pour plus d'informations.",
    174 : "Blogue",
    175 : "Tout voir",
    176 : "Chargement...",
    177 : " Envoi",
    178 : "Voulez vous quitter ?",
    179 : "Non",
    180 : "Sortir",
    181 : "Filtre",
    182 : "Trier par",
    183 : "Ascendant (A-Z)",
    184 : "Descendant (Z-A)",
    185 : "Prix",
    186 : "Réinitialiser le filtre",
    187 : "Appliquer le filtre",
    188 : "Mon adresse",
    189 : "Adresse introuvable",
    190 : "Accueil",
    191 : "Bureau",
    192 : "Autre",
    193 : "Définir l'emplacement",
    194 : "Trouvez des services près de chez vous",
    195 : "En autorisant l'accès à la localisation, vous pouvez rechercher des services et des fournisseurs proches de chez vous.",
    196 : "Utiliser l'emplacement des courants",
    197 : "Définir à partir de la carte",
    198 : "Votre localisation actuelle est maintenant enregistrée. Si le Service demandé doit se faire ailleurs, nous vous contacterons pour que vous indiquez l'endroit précis. Appuyer sur le bouton en dessous pour valider votre demande. ",
    199 : "Étiqueter comme",
    200 : "Adresse de livraison",
    201 : "Entrez l'adresse de livraison",
    202 : "Nom du contact",
    203 : "Entrez le nom du contact",
    204 : "Numéro de téléphone de contact",
    205 : "Entrez le numéro de téléphone du contact",
    206 : "Enregistrer l'emplacement",
    207 : "Latitude",
    208 : "Longitude",
    209 : "Veuillez entrer le téléphone",
    210 : "par l'administrateur",
    211 : "par fournisseur",
    212 : "par client",
    213 : "Saisir l'adresse",
    214 : "Adresse actuelle",
    215 : "Autres adresses",
    216 : "Localisation",
    217 : "Votre adresse est en dehors de la zone de travail du fournisseur",
    218 : "Voir détails",
    219 : "Demandes spéciales",
    220 : "Emplacement du fournisseur",
    221 : "Modules complémentaires",
    222 : "À proximité de vous",
    223 : "Loin",
    224 : "Prestataires",
    225 : "Veuillez saisir un code valide",
    226 : "Votre numéro de téléphone a été vérifié. Vous ne pouvez pas modifier le numéro de téléphone",
    227 : "Mot de passe oublié ?",
    228 : "Réinitialiser le mot de passe",
    229 : "Envoyer un nouveau mot de passe",
    230 : "E-mail de réinitialisation du mot de passe envoyé. Veuillez vérifier votre messagerie.",
    231 : "Le",
    232 : "Identifiant",
    233 : "Veuillez entrer du texte",
    234 : "Veuillez saisir le code",
    235 : "Sous-total",
    236 : "Remise",
    237 : "Sous-catégorie",
    238 : "Partager cette application",
    239 : "Services à proximité",
    240 : "Ouvrir la page du fournisseur",
    241 : "Rapport ...",
    242 : "Bloquer l'utilisateur",
    243 : "Bloquer",
    244 : "Ils ne pourront pas vous envoyer de message. Vous ne pourrez pas leur envoyer de message. Ils ne seront pas avertis que vous les avez bloqués.",
    245 : "Utilisateur",
    246 : "Annuler",
    247 : "bloqué",
    248 : "Pourquoi signalez-vous cet utilisateur ?",
    249 : "Votre signalement est anonyme, sauf si vous signalez une violation de la propriété intellectuelle.",
    250 : "Merci de nous l'avoir fait savoir",
    251 : "Vos commentaires sont importants pour nous aider à assurer la sécurité de la communauté.",
    252 : "Débloquer",
    253 : "Ils pourront vous envoyer un message. Vous pourrez leur envoyer un message. Ils ne seront pas avertis que vous les avez débloqués.",
    254 : "débloqué",
    255 : "Vos fournisseurs favoris",
    256 : "Voir vos fournisseurs favoris",
    257 : "Fournisseurs favoris",
    258 : "Activer la notification",
    259 : "Non disponible maintenant",
    260 : "Prestations",
    261 : "Produits fournisseur",
    262 : "Non disponible maintenant",
    263 : "Montant total",
    264 : "Ajouter au panier",
    265 : "Veuillez sélectionner une variante",
    266 : "en stock",
    267 : "Produit ajouté au panier",
    268 : "Chariot",
    269 : "Mon panier",
    270 : "Passer à la caisse",
    271 : "Votre panier est vide",
    272 : "Prix de l'article",
    273 : "Ce service déjà dans le panier",
    274 : "Ce produit déjà dans le panier",
    275 : "Service ajouté au panier",
    276 : "TVA/IMPÔT",
    277 : "Voir plus",
    278 : "Produits",
    279 : "Rechercher des produits",
    280 : "Trier par fournisseur",
    281 : "Ne pas sélectionner",
    282 : "Produits associés",
    283 : "Autres produits",
    284 : "Réservation à",
    285 : "Montant d'achat minimum pour ce fournisseur : ",
    286 : "Montant d'achat maximum pour ce fournisseur : ",
    287 : "@ ModjiDep 2022",
    288 : "Un dépannage parfait à portée de main",
    289 : "Indisponible",
    290 : "Demander",
    291 : "Continuer",
    292 : "Vérifiez votre connexion Internet !",
    293 : "Par TigerSoft",
    294 : "Voir les commentaires",
    295 : "Prêt",
    296 : "Terminé",
    297 : "Annulé",
    298 : "Accepté",
    299 : "Chargement des messages...",
    300 : "Aucune notification",
    301 : "Vérification éffectuée avec succès. Bienvenu(e) parmi nous.",
    302 : "Des mises à jour sont disponibles. Rendez-vous sur PlayStore ou l'appStore pour obtenir la dernière version.",
    303 : "Aucune Offre pour l'instant!",
  };



  Map<int, String> langAra = {
  0: "ModjiDep" ,
  1: "V 1.0" ,
  2: "إرسال" ,
  3: "اللغة" ,
  4: "اللغة المفضلة" ,
  5: "حدد اللغة المفضلة" ,
  6: "الصفحة الرئيسية" ,
  7: "مناقشة" ,
  8: "حجز",
  9: "الحساب" ,
  10: "تغيير اللغة" ,
  11: "حدد لغتك المفضلة" ,
  12: "تمكين الوضع المظلم" ,
  13: "اضبط الوضع المفضل لديك" ,
  14: "سياسة الخصوصية" ,
  15: "تعرف على سياسة الخصوصية الخاصة بنا" ,
  16: "انقر لعرض الملف الشخصي" ,
  17: "تسجيل الخروج" ,
  18: "إغلاق الجلسة" ,
  19: "إشعارات" ,
  20: "الكثير من المعلومات المهمة" ,
  21: "الاسم" ,
  22: "أدخل اسمك" ,
  23: "البريد الإلكتروني" ,
  24: "أدخل بريدك الإلكتروني" ,
  25: "رقم الهاتف" ,
  26: "أدخل رقم هاتفك" ,
  27: "العنوان" ,
  28: "أدخل عنوان العميل" ,
  29: "الوصف" ,
  30: "أدخل وصفا موجزا عن نفسك" ,
  31: "حفظ" ,
  32: "تغيير كلمة المرور" ,
  33: "كلمة المرور الجديدة" ,
  34: "أدخل كلمة المرور" ,
  35: "تأكيد كلمة المرور الجديدة" ,
  36: "أدخل كلمة المرور" ,
  37: "تغيير كلمة المرور" ,
  38: "ملفي الشخصي" ,
  39: "كل شيء عنك" ,
  40: "حرجة" ,
  41: "اقرأ الكل" ,
  42: "متوسط التصنيفات" ,
  43: "اتصل الآن",
  44: "كلمة المرور" ,
  45: "أدخل كلمة المرور الخاصة بك" ,
  46: "متابعة" ,
  47: "تسجيل" ,
  48: "أو متابعة" ,
  49: "تسجيل" ,
  50: "في أقل من دقيقة" ,
  51: "تأكيد كلمة المرور" ,
  52: "التحقق" ,
  53: "سنرسل لك رمز التحقق." ,
  54: "لقد أرسلنا رمز تحقق مكونًا من 6 أرقام." ,
  55: "أدخل الرمز" ,
  56: "أدخل الرمز المكون من 6 أرقام" ,
  57: "اكتب رسالتك ..." ,
  58: "جديد" ,
  59: "مقبولة" ,
  60: "قيد التقدم" ,
  61: "تم" ,
  62: "ملغاة",
  63: "التاريخ" ,
  64: "اتصال" ,
  65: "رسالة" ,
  66: "المعرف" ,
  67: "الانتظار",
  68: "الحجز مقبول",
  69: "تم القبول في",
  70: "ابدأ مهمة" ,
  71: "مخطط" ,
  72: "اكتملت المهمة" ,
  73: "سيظهر الدفع هنا" ,
  74: "التسعير" ,
  75: "الكمية" ,
  76: "مبلغ الضريبة" ,
  77: "المجموع" ,
  78: "طلب",
  79: "الدفع" ,
  80: "إجراء الدفع" ,
  81: "الدفع النقدي" ,
  82: "تأكيد الدفع" ,
  83: "مراجعة" ,
  84: "اترك مراجعة" ,
  78: "طلب",
  86: "اكتب رأيك" ,
  87: "أخبرنا عن هذه الخدمة" ,
  88: "اضغط على النجوم لتقييم هذه الخدمة" ,
  89: "إرسال مراجعة" ,
  90: "إضافة صور" ,
  91: "من المعرض" ,
  92: "من الكاميرا" ,
  93: "كيف نساعدك؟" ,
  94: "اعثر على ما تريد" ,
  95: "بحث سريع" ,
  96: "إعلام" ,
  97: "المدة" ,
  98: "دقيقة" ,
  99: "قد تستغرق هذه الخدمة ما يصل إلى" ,
  100: "المعارض" ,
  101: "التعليقات والتقييمات" ,
  102: "احجز هذه الخدمة" ,
  103: "عنوانك" ,
  104: "إضافة جديد" ,
  105: "تلميح" ,
  106: "هل هناك شيء آخر" ,
  107: "رمز القسيمة" ,
  108: "تطبيق" ,
  109: "في أي وقت" ,
  110: "جدولة طلب" ,
  111: "الخدمة المطلوبة في" ,
  112: "حدد التاريخ والوقت" ,
// 113: "تأكيد وحجز الآن" ,
  113: "تأكيد" ,
  114: "حسنًا" ,
  115: "تم تقديم حجزك بنجاح , ستتلقى تأكيدًا قريبًا.",
  116: "شكرا لك!" ,
  117: "إضافة عنوان" ,
  118: "بيتي" ,
  119: "العنوان الكامل" ,
  120: "حدد العنوان" ,
  121: "اختر هنا" ,
  122: "بحث" ,
  123: "الاثنين" ,
  124: "الثلاثاء" ,
  125: "الأربعاء" ,
  126: "الخميس" ,
  127: "الجمعة" ,
  128: "السبت" ,
  129: "الأحد" ,
  130: "ثابت" ,
  131: "جدول",
  132: "البدء من",
  133: "الرجاء إدخال العنوان" ,
  134: "الرجاء تحديد العنوان" ,
  135: "الرجاء إدخال بريد إلكتروني" ,
  136: "الرجاء إدخال كلمة المرور" ,
  137: "المستخدم غير موجود" ,
  138: "المستخدم لا ينشئ" ,
  139: "بريد إلكتروني خاطئ" ,
  140: "كلمات المرور غير متساوية" ,
  141: "يجب أن يكون رقم الهاتف" ,
  142: "الرموز" ,
  143: "تم إرسال الرمز. يرجى التحقق من هاتفك بحثًا عن رمز التحقق.",
  144: "مهلة" ,
  145: "اليوم" ,
  146: "عنا" ,
  147: "نحن معروفون" ,
  148: "الشروط العامة" ,
  149: "الشروط العامة المعروفة" ,
  150: "غير موجود ..." ,
  151: "أدخل تأكيد كلمة المرور" ,
  152: "تم تغيير كلمة المرور" ,
  153: "الرجاء إدخال الاسم" ,
  154: "البيانات المحفوظة" ,
  155: "المورد" ,
  156: "مشاركة الدردشة" ,
  157: "وصل الحجز الجديد" ,
  158: "الحالة الآن:" ,
  159: "تم تعديل حالة التحفظ" ,
  160: "من المستخدم:" ,
  161: "قيم هذه الخدمة",
  162: "القسيمة غير موجودة",
  163: "القسيمة نشطة",
  164: "قسيمة غير معتمدة من قبل هذا المورد" ,
  165: "القسيمة لا تدعم هذه الفئة" ,
  166: "القسيمة لا تدعم هذه الخدمة" ,
  167: "قسيمة" ,
  168: "لا" ,
  169: "القسيمة انتهت صلاحيتها" ,
  170: "مفضلاتك" ,
  171: "شاهد خدماتك المفضلة" ,
  172: "خدمات ممتازة" ,
  173: "تم تعطيل المستخدم. قم بتسجيل الدخول إلى المسؤول للحصول على مزيد من المعلومات.",
  174: "مدونة" ,
  175: "انظر جميع" ,
  176: "جارٍ التحميل ..." ,
  177: "شحنة" ,
  178: "هل تريد الإقلاع عن التدخين؟" ,
  179: "لا" ,
  180: "خروج" ,
  181: "تصفية" ,
  182: "فرز حسب",
  183: "تصاعدي (أ-ي)" ,
  184: "تنازلي (ي - أ)" ,
  185: "السعر" ,
  186: "إعادة تعيين عامل التصفية" ,
  187: "تطبيق الفلتر" ,
  188: "عنواني" ,
  189: "لم يتم العثور على العنوان" ,
  190: "الصفحة الرئيسية" ,
  191: "مكتب" ,
  192: "أخرى" ,
  193: "تعيين الموقع" ,
  194: "البحث عن خدمات بالقرب منك" ,
  195: "بالسماح بالوصول إلى الموقع , يمكنك البحث عن الخدمات والموفرين بالقرب منك." ,
  196: "استخدام موقع التيارات" ,
  197: "تعيين من الخريطة" ,
  198: "تم حفظ موقعك الحالي الآن. إذا كان سيتم تنفيذ الخدمة المطلوبة في مكان آخر ، فسوف نتصل بك للإشارة إلى الموقع المحدد. اضغط على الزر أدناه للتحقق من صحة طلبك." ,
  199: "تصنيف كـ" ,
  200: "عنوان التسليم" ,
  201: "أدخل عنوان التسليم" ,
  202: "اسم جهة الاتصال" ,
  203: "أدخل اسم جهة الاتصال" ,
  204: "رقم هاتف الاتصال" ,
  205: "أدخل رقم هاتف جهة الاتصال" ,
  206: "حفظ الموقع",
  207: "خط العرض" ,
  208: "خط الطول" ,
  209: "الرجاء إدخال الهاتف" ,
  210: "بواسطة المسؤول",
  211: "حسب المزود",
  212: "حسب الزبون",
  213: "أدخل العنوان" ,
  214: "العنوان الحالي" ,
  215: "عناوين أخرى" ,
  216: "الموقع" ,
  217: "عنوانك خارج منطقة عمل المزود" ,
  218: "انظر التفاصيل" ,
  219: "الطلبات الخاصة" ,
  220: "موقع المزود" ,
  221: "الإضافات" ,
  222: "بالقرب منك" ,
  223: "بعيد" ,
  224: "الموفرون" ,
  225: "الرجاء إدخال رمز صالح" ,
  226: "تم التحقق من رقم هاتفك. لا يمكنك تعديل رقم الهاتف" ,
  227: "هل نسيت كلمة المرور؟" ,
  228: "إعادة تعيين كلمة المرور" ,
  229: "إرسال كلمة مرور جديدة" ,
  230: "تم إرسال البريد الإلكتروني لإعادة تعيين كلمة المرور. يرجى التحقق من بريدك.",
  231: "ال" ,
  232: "معرف" ,
  233: "الرجاء إدخال نص" ,
  234: "الرجاء إدخال الرمز" ,
  235: "المجموع الفرعي" ,
  236: "خصم" ,
  237: "فئة فرعية" ,
  238: "مشاركة هذا التطبيق" ,
  239: "خدمات قريبة" ,
  240: "فتح صفحة الموفر" ,
  241: "تقرير ..." ,
  242: "حظر المستخدم" ,
  243: "بلوك" ,
  244: "لن يتمكنوا من مراسلتك. لن تتمكن من مراسلتهم. لن يتم إخطارهم بأنك حظرتهم." ,
  245: "المستخدم" ,
  246: "إلغاء" ,
  247: "ممنوع",
  248: "لماذا تبلغ عن هذا المستخدم؟" ,
  249: "التقرير الخاص بك مجهول , إلا إذا كنت تقوم بالإبلاغ عن انتهاك للملكية الفكرية." ,
  250: "شكرًا لإعلامنا" ,
  251: "ملاحظاتك مهمة في مساعدتنا في الحفاظ على المجتمع آمنًا.",
  252: "إلغاء الحظر" ,
  253: "يمكنهم مراسلتك. يمكنك مراسلتهم. لن يتم إعلامهم بأنك قمت بإلغاء حظرهم." ,
  254: "غير محظور",
  255: "مزودو الخدمات المفضلون" ,
  256: "عرض مقدمي الخدمات المفضلة لديك" ,
  257: "المزودون المفضلون" ,
  258: "تمكين الإعلام" ,
  259: "غير متوفر الآن" ,
  260: "الخدمات" ,
  261: "منتجات الموفر" ,
  262: "غير متوفر الآن" ,
  263: "المبلغ الإجمالي" ,
  264: "إضافة إلى عربة التسوق" ,
  265: "الرجاء تحديد البديل" ,
  266: "متوفر",
  267: "تمت إضافة المنتج إلى سلة التسوق" ,
  268: "العربة" ,
  269: "عربتي" ,
  270: "تابع الدفع" ,
  271: "عربة التسوق الخاصة بك فارغة" ,
  272: "سعر السلعة" ,
  273: "هذه الخدمة موجودة بالفعل في عربة التسوق" ,
  274: "هذا المنتج موجود بالفعل في سلة التسوق" ,
  275: "تمت إضافة الخدمة إلى سلة التسوق" ,
  276: "ضريبة القيمة المضافة / الضرائب" ,
  277: "مشاهدة المزيد" ,
  278: "المنتجات" ,
  279: "البحث عن المنتجات" ,
  280: "فرز حسب الموفر",
  281: "لم تحدد" ,
  282: "منتجات ذات صلة" ,
  283: "منتجات أخرى" ,
  284: "الحجز في" ,
  285: "الحد الأدنى لمبلغ الشراء لهذا الموفر:" ,
  286: "الحد الأقصى لمبلغ الشراء لهذا الموفر:" ,
  287: "@ ModjiDep 2022",
  288: "استكشاف الأخطاء وإصلاحها بشكل مثالي في متناول يدك" ,
  289: "غير متوفر" ,
  290: "اسأل" ,
  291: "يكمل" ,
  292: "تحقق من اتصالك بالإنترنت!" ,
  293: "بواسطة TigerSoft" ,
  294: "انظر التعليقات" ,
  295: "جاهز" ,
  296: "انتهى" ,
  297: "ملغاة",
  298: "مقبولة" ,
  299: "جارٍ تحميل الرسائل ..." ,
  300: "لا يوجد إشعار" ,
  301: "اكتمل التحقق بنجاح. اهلا وسهلا بيننا.",
  302 : "التحديثات متوفرة. انتقل إلى PlayStore أو appStore للحصول على أحدث إصدار.",
  303 : "لا يوجد عرض بعد!",
  };




  Map<String, dynamic>? defaultLang;

  setLang(Map<String, dynamic> _def, String _locale, BuildContext context, TextDirection _direction){
    defaultLang = _def;
    locale = _locale;
    direction = _direction;
    Provider.of<LanguageChangeNotifierProvider>(context,listen:false).changeLocale(locale);
  }

  String get(int id){
    dprint(locale);
    if (defaultLang == null) {
      return langEng[id] == null ? "" : langEng[id]!;
    }else{
      /*
      if (defaultLang![id.toString()] != null) {
        return defaultLang![id.toString()];
      }
      */
        if(locale == "en") {
          return langEng[id] == null ? "" : langEng[id]!;
        }else if(locale == "fr"){
          return langFra[id] == null ? "" : langFra[id]!;
        }else if (locale == "ar"){
          return langAra[id] == null ? "" : langAra[id]!;
        }else{
          return langFra[id] == null ? "" : langEng[id]!;
        }
    }
  }
}

